services:
  web:
    image: jmixtest/jmix-pm
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    mem_limit: 2g
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: myprojectmanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
